#!/bin/bash
# Combine Stage1 (lexer) + Stage2 (parser) + Stage5 (codegen) into a single
# self-host source file, removing duplicate declarations and the per-stage
# `main()` functions (we keep only stage5's main, which ties everything together).
#
# Output: /home/z/my-project/yiltc/yilt-selfhost/src/combined.yilt

set -e

SRC=/home/z/my-project/yiltc/yilt-selfhost/src
OUT="$SRC/combined.yilt"

# stage1/lexer.yilt: drop everything from "Section 14: Main entry point" onward
# stage2/parser.yilt: drop lines 1-111 (T_* constants + Token struct: duplicates of stage1),
#                     then drop everything from "Section 10: Main entry point" onward
# stage5/codegen.yilt: keep as-is (its main is the real entry point)

# Find the line number where "Main entry point" section starts in stage1
STAGE1_MAIN=$(grep -n "Main entry point" "$SRC/stage1/lexer.yilt" | head -1 | cut -d: -f1)
STAGE1_END=$((STAGE1_MAIN - 2))  # -2 to skip the section header comment

# Find the line number where "Main entry point" section starts in stage2
STAGE2_MAIN=$(grep -n "Main entry point" "$SRC/stage2/parser.yilt" | head -1 | cut -d: -f1)
STAGE2_END=$((STAGE2_MAIN - 2))

{
  echo "// ==========================================================================="
  echo "// Yilt Self-Host Compiler — Combined (Stage 1 + Stage 2 + Stage 5)"
  echo "// ==========================================================================="
  echo "// AUTO-GENERATED by scripts/combine_yilt.sh — do not edit directly."
  echo "//"
  echo "// This file is what gets fed to Go-yiltc to produce a native binary that"
  echo "// can itself compile a subset of Yilt to native ELF binaries."
  echo "// ==========================================================================="
  echo ""
  echo "// ==========================================================================="
  echo "// SECTION 1: Lexer  (originally stage1/lexer.yilt, main() stripped)"
  echo "// ==========================================================================="
  head -n "$STAGE1_END" "$SRC/stage1/lexer.yilt"
  echo ""
  echo "// ==========================================================================="
  echo "// SECTION 2: Parser  (originally stage2/parser.yilt, T_*/Token/main stripped)"
  echo "// ==========================================================================="
  echo "// --- skipped stage2 lines 1-111 (T_* constants + Token struct: duplicates of stage1)"
  tail -n +112 "$SRC/stage2/parser.yilt" | head -n $((STAGE2_END - 111))
  echo ""
  echo "// ==========================================================================="
  echo "// SECTION 3: Code Generator  (originally stage5/codegen.yilt)"
  echo "// ==========================================================================="
  cat "$SRC/stage5/codegen.yilt"
} > "$OUT"

echo "Combined file: $OUT"
wc -l "$OUT"
